language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - ES_URL=http://127.0.0.1:9200

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

before_install:
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.4.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearc

before_script:
  - composer install
  - composer global require maglnet/composer-require-checker && $HOME/.composer/vendor/bin/composer-require-checker

script: vendor/bin/phpunit tests

after_success:
  - docker run --rm -v $(pwd):/app nyholm/roave-bc-check roave-backwards-compatibility-check:assert-backwards-compatible --from=$(git describe --tags $(git rev-list --tags --max-count=1))
