version: '3.7'

services:
  php:
    image: "php:7.2"
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      - "ES_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
